version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nct_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_HOST: nct_db
      DB_PORT: 3306
      DB_DATABASE: nct
      DB_USERNAME: nct
      DB_PASSWORD: secret
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nct_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  database:
    image: mysql:5.7.22
    container_name: nct_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nct
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=nct
      - MYSQL_PASSWORD=secret
    volumes:
      - dbdata:/var/lib/mysql/
    expose:
      - 3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
